In [32]:
import torch
import torch.nn as nn
import numpy as np
# np.random.seed(42)
x=torch.tensor([1,2,3,4,5,6,7,8,9,10])
y=torch.tensor([0,1,0,1,0,1,0,1,0,1])
print(x)
print(y)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])


In [33]:
class SimpleNeuralNetwork:
    def __init__(self):
        self.weights = torch.randn(1,requires_grad=True)
        self.bias = torch.randn(1,requires_grad = True)
    def forward(self,x):
        return self.weights *x +self.bias
    def loss(self,y_pred,y):
        return ((y_pred-y)**2).mean()

In [34]:
model = SimpleNeuralNetwork()
print(model.weights)
print(model.bias)

tensor([-0.8717], requires_grad=True)
tensor([-0.5626], requires_grad=True)


In [35]:
#training loop
for _ in range(10):
    y_pred =model.forward(x)
    loss=model.loss(y_pred,y)
    # print(loss)
    loss.backward()
    with torch.no_grad():
        model.weights -=0.01* model.weights.grad
        model.bias -= 0.01*model.bias.grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(loss)

tensor(41.2611, grad_fn=<MeanBackward0>)
tensor(2.2387, grad_fn=<MeanBackward0>)
tensor(0.4473, grad_fn=<MeanBackward0>)
tensor(0.3642, grad_fn=<MeanBackward0>)
tensor(0.3594, grad_fn=<MeanBackward0>)
tensor(0.3583, grad_fn=<MeanBackward0>)
tensor(0.3573, grad_fn=<MeanBackward0>)
tensor(0.3563, grad_fn=<MeanBackward0>)
tensor(0.3554, grad_fn=<MeanBackward0>)
tensor(0.3544, grad_fn=<MeanBackward0>)


In [37]:
import numpy as np
import cv2
import os

os.makedirs("square",exist_ok=True)
os.makedirs("circle",exist_ok=True)

img_size=128

def generate_square():
    img =np.zeros((img_size,img_size),dtype=np.uint8)
    start = np.random.randint(10,30)
    size = np.random.randint(20,50)
    img[start:start+size,start:start+size]=255
    return img
def generate_circle():
    img = np.zeros((img_size,img_size),dtype = np.uint8)
    center = (np.random.randint(30,98),np.random.randint(30,98))
    radius = np.random.randint(10,30)
    cv2.circle(img,center,radius,255,-1)

    return img
for i in range(30):
    square_img = generate_square()
    cv2.imwrite(f"square/square_{i}.png",square_img)
    circle_img = generate_circle()
    cv2.imwrite(f"circle/circle_{i}.png",circle_img)
