In [2]:
import torch

In [9]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
my_tensor=torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32,device=device,requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)
torch.float32
cpu
torch.Size([3, 3])
True


In [14]:
x=torch.empty(size=(3,4))
print(x)
x=torch.zeros((3,4))
print(x)
x=torch.rand((3,4))
print(x)
x=torch.ones((3,4))
print(x)
x=torch.eye(5,5)
print(x)

tensor([[7.1483e-12, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [5.7581e-15, 0.0000e+00, 1.0842e-19, 0.0000e+00],
        [4.6241e+30, 1.0552e+24, 5.5757e-02, 1.8728e+31]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.6825, 0.2524, 0.0770, 0.2828],
        [0.7610, 0.7429, 0.1381, 0.6457],
        [0.9847, 0.5166, 0.3274, 0.4203]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [17]:
x=torch.arange(start=0,end=10,step=2)
print(x)
x=torch.linspace(start=0.1,end=1,steps=10)
print(x)
x=torch.empty(size=(2,5)).normal_(mean=0,std=1)
print(x)
x=torch.empty(size=(2,5)).uniform_(0,1)
print(x)
x=torch.diag(torch.ones(3))
print(x)

tensor([0, 2, 4, 6, 8])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-0.5267,  0.5005,  0.9240,  0.4810,  1.8177],
        [ 0.1443, -0.6488,  0.4476,  0.8229, -1.5242]])
tensor([[0.0564, 0.3309, 0.4253, 0.4786, 0.2408],
        [0.9884, 0.2375, 0.2436, 0.3159, 0.3233]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [18]:
tensor=torch.arange(12)
print(tensor)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int16)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float16)
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)


In [19]:
import numpy as np
np_array= np.zeros((5,5))
print(np_array)
tensor=torch.from_numpy(np_array)
print(tensor)
np_array_back=tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
