In [1]:
import torch

In [7]:
x=torch.tensor([1,2,3,4,5])
y=torch.tensor([6,7,8,9,10])

#addition
z1=x+y
z2=torch.add(x,y)
z3=torch.empty(5)
torch.add(x,y,out=z3)
print(z1,z2,z3)

z=x-y
print(z)
z=torch.true_divide(x,y)
print(z)

t=x*y
print(t)

m=torch.zeros(5)
m.add_(x)
print(m)
m+=x

## exponentiation
z=x.pow(2)
print(z)
z=x**2
print(z)


tensor([ 7,  9, 11, 13, 15]) tensor([ 7,  9, 11, 13, 15]) tensor([ 7.,  9., 11., 13., 15.])
tensor([-5, -5, -5, -5, -5])
tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])
tensor([ 6, 14, 24, 36, 50])
tensor([1., 2., 3., 4., 5.])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])


In [10]:
#comparison
z=x>0
print(z)

#matrix multiplication
x1=torch.rand(2,5)
x2=torch.rand(5,3)
x3=torch.mm(x1,x2)
print(x3)
x3=x1.mm(x2)
print(x3)

matrix_exp=torch.rand(5,5)
print(matrix_exp)
print(matrix_exp.matrix_power(3))

tensor([True, True, True, True, True])
tensor([[0.9569, 1.0432, 0.8099],
        [0.5972, 0.8915, 0.7185]])
tensor([[0.9569, 1.0432, 0.8099],
        [0.5972, 0.8915, 0.7185]])
tensor([[0.3182, 0.7008, 0.3139, 0.3427, 0.0781],
        [0.5319, 0.3389, 0.6400, 0.4107, 0.8387],
        [0.4966, 0.6103, 0.8697, 0.5807, 0.3340],
        [0.8259, 0.5716, 0.6889, 0.6489, 0.4523],
        [0.1488, 0.1255, 0.0157, 0.3868, 0.6724]])
tensor([[2.1008, 2.1763, 2.3475, 2.1816, 2.1435],
        [2.8744, 2.8561, 3.1150, 2.9383, 2.9709],
        [3.4643, 3.5341, 3.8801, 3.5294, 3.4483],
        [3.6311, 3.6706, 4.0359, 3.6716, 3.6450],
        [1.2512, 1.2408, 1.2695, 1.3118, 1.3546]])


In [ ]:
z=x*y
print(z)
z=torch.dot(x,y)
print(z)


tensor([ 6, 14, 24, 36, 50])
tensor(130)


In [14]:
batch=32
n=10
m=20
p=30
tensor1=torch.rand(batch,n,m)
tensor2=torch.rand(batch,m,p)
out_bmm=torch.bmm(tensor1,tensor2)
print(out_bmm.shape)
print(out_bmm)

torch.Size([32, 10, 30])
tensor([[[3.8316, 4.8705, 3.4939,  ..., 4.6159, 3.3843, 4.0711],
         [4.2622, 4.7006, 4.0028,  ..., 5.1047, 3.4480, 4.4049],
         [6.5826, 6.0125, 4.4168,  ..., 5.4084, 5.7545, 5.2520],
         ...,
         [3.7075, 3.9698, 2.8013,  ..., 3.4932, 3.5294, 3.1373],
         [6.0808, 5.6401, 4.7803,  ..., 4.8852, 5.1184, 5.1177],
         [5.6508, 6.9214, 5.1828,  ..., 6.4262, 5.7634, 5.4404]],

        [[5.1819, 7.7495, 5.2734,  ..., 5.3308, 6.5743, 5.0799],
         [3.9074, 5.3438, 3.5225,  ..., 3.3557, 3.4994, 3.7083],
         [4.2080, 5.0608, 4.9421,  ..., 4.9145, 4.2647, 3.3630],
         ...,
         [4.7366, 5.3908, 4.1725,  ..., 4.2055, 5.5825, 4.4275],
         [4.5741, 5.9671, 4.3117,  ..., 3.7188, 4.0099, 3.7815],
         [4.8325, 6.1455, 4.9165,  ..., 4.7623, 4.7152, 4.6619]],

        [[5.1638, 4.3629, 4.2000,  ..., 4.5207, 4.4121, 4.8939],
         [6.1904, 3.8935, 5.5048,  ..., 5.0614, 5.0041, 5.6077],
         [7.1328, 4.4015, 5.9471,

In [16]:
x1=torch.rand((5,5))
x2=torch.rand((1,5))
z=x1-x2
print(z)
z=x1**x2
print(z)

tensor([[ 0.8063,  0.4764,  0.0512,  0.2464,  0.3911],
        [ 0.9596,  0.1532, -0.0164,  0.2149,  0.5733],
        [ 0.1830,  0.3990,  0.5174,  0.2347,  0.0233],
        [ 0.7314, -0.0506,  0.0265, -0.2059,  0.3383],
        [ 0.6340,  0.0855, -0.0722, -0.3973,  0.5602]])
tensor([[0.9948, 0.9596, 0.7342, 0.8410, 0.9052],
        [0.9997, 0.7935, 0.6879, 0.8243, 0.9807],
        [0.9557, 0.9234, 0.9890, 0.8348, 0.7081],
        [0.9920, 0.6595, 0.7177, 0.5206, 0.8812],
        [0.9881, 0.7524, 0.6466, 0.1531, 0.9756]])


In [17]:
sum_x=torch.sum(x,dim=0)
print(sum_x)
values,indices=torch.max(x,dim=0)
values1,indices1=torch.min(x,dim=0)
print(values,indices)
print(values1,indices1)
abs_x=torch.abs(x)
print(abs_x)
z=torch.argmax(x,dim=0)
print(z)
z=torch.argmin(x,dim=0)
print(z)
mean_x=torch.mean(x.float(),dim=0)
print(mean_x)
z=torch.eq(x,y)
print(z)
sorted_y,indices=torch.sort(y,dim=0,descending=False)
print(sorted_y,indices)
z=torch.clamp(x,min=0,max=5)
print(z)

tensor(15)
tensor(5) tensor(4)
tensor(1) tensor(0)
tensor([1, 2, 3, 4, 5])
tensor(4)
tensor(0)
tensor(3.)
tensor([False, False, False, False, False])
tensor([ 6,  7,  8,  9, 10]) tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3, 4, 5])


In [18]:
x=torch.tensor([1,0,1,0,1],dtype=torch.bool)
z=torch.any(x)
print(z)
z=torch.all(x)
print(z)


tensor(True)
tensor(False)
