In [1]:
import torch

In [10]:
batch_size=10
features=25
x=torch.rand((batch_size,features))
print(x[0].shape)
print(x[:,0].shape)
print(x[2,0:10].shape)
x[0,0]=100
print(x[0])
x=torch.arange(10)
indices=[2,5,8]
print(x[indices])

x=torch.rand((3,5))
rows=torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x.shape)
print(x[rows].shape)
print(x[:,cols].shape)
print(x[rows,cols].shape)

torch.Size([25])
torch.Size([10])
torch.Size([10])
tensor([1.0000e+02, 3.9099e-01, 4.1641e-01, 3.3506e-01, 3.5257e-01, 1.3503e-01,
        2.4434e-01, 1.2091e-02, 4.2204e-01, 1.4114e-01, 3.4109e-01, 7.4785e-01,
        3.8352e-01, 1.1707e-01, 6.8021e-01, 6.9223e-01, 5.1898e-01, 4.3768e-01,
        3.6617e-02, 3.0828e-01, 1.0410e-01, 6.2924e-01, 3.7312e-01, 2.6129e-01,
        6.1851e-02])
tensor([2, 5, 8])
torch.Size([3, 5])
torch.Size([2, 5])
torch.Size([3, 2])
torch.Size([2])


In [13]:
x=torch.arange(10)
print(x[(x<3)|(x>7)])
print(x[x.remainder(2)==0])
print(x[x.remainder(2)==1])

tensor([0, 1, 2, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])


In [18]:
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10
